spring:
  thymeleaf:
    prefix : classpath:/templates/
    suffix : .html
    mode: LEGACYHTML5
    cache: false
    servlet:
      content-type: text/html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
    encoding:
      force: true
  devtools:
    restart:
      enabled: true
  cache:
    type: ehcache
    ehcache:
      config: config/ehcache.xml
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.uploadPath}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.bootdo.**.domain
web:
  uploadPath: static/